--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/laith98/LoginUI
build-by-default: true
branches:
- master
projects:
  LoginUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
